[package]
name = "elgin"
version = "0.0.1"
authors = ["jch"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llvm-sys = "100"
lazy_static = "*"
